version: '2'

services:
  mysql:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - db:/var/lib/mysql
    ports:
      - '3306:3306'
    restart: always
    
  php:
    build: ./php
    ports:
      - '80:80'
    volumes:
      - ./html:/var/www/html
    depends_on:
      - mysql
    restart: always

volumes:
  db:
